
version: '3.9'
services:
  app:
    build: 
      context: .
      dockerfile: "Dockerfile"
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - kafka

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
    - ./.docker/redis/data:/root/redis
    - ./.docker/redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass my-password

  migrate:
    build:
      context: ./internal/core/infra/database/migrations/
      dockerfile: "Dockerfile"
    container_name: migrate
    volumes:
      - ./internal/core/infra/database/migrations:/migrations
    entrypoint: dockerize -wait tcp://mgmt_db:5432 -timeout 20s migrate
    command: [ "-path", "/migrations", "-database",  "postgres://postgres:postgres@mgmt_db:5432/mgmt?sslmode=disable", "-verbose","up" ]
    depends_on:
      - mgmt_db

  mgmt_db:
    container_name: mgmt_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: mgmt
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/mgmt_db:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080

  kafka:
    image: bitnami/kafka:latest
    restart: on-failure
    volumes:
      - ./.docker/kafka/data:/bitnami
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_NUM_PARTITIONS=3
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    depends_on:
      - kafka
      - zookeeper
    ports:
      - "8087:8080"
    restart: always
    environment:
      - KAFKA_CLUSTERS_0_NAME=notification
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181